const country_names = {
    AF: 'Afghanistan',
    AL: 'Albania',
    DZ: 'Algeria',
    AD: 'AndorrA',
    AO: 'Angola',
    AI: 'Anguilla',
    AQ: 'Antarctica',
    AR: 'Argentina',
    AM: 'Armenia',
    AW: 'Aruba',
    AU: 'Australia',
    AT: 'Austria',
    AZ: 'Azerbaijan',
    BS: 'Bahamas',
    BH: 'Bahrain',
    BD: 'Bangladesh',
    BB: 'Barbados',
    BY: 'Belarus',
    BE: 'Belgium',
    BZ: 'Belize',
    BJ: 'Benin',
    BM: 'Bermuda',
    BT: 'Bhutan',
    BO: 'Bolivia',
    BW: 'Botswana',
    BR: 'Brazil',
    BG: 'Bulgaria',
    BI: 'Burundi',
    KH: 'Cambodia',
    CM: 'Cameroon',
    CA: 'Canada',
    TD: 'Chad',
    CL: 'Chile',
    CN: 'China',
    CO: 'Colombia',
    KM: 'Comoros',
    CG: 'Congo',
    CI: "Cote D'Ivoire",
    HR: 'Croatia',
    CU: 'Cuba',
    CY: 'Cyprus',
    DK: 'Denmark',
    DJ: 'Djibouti',
    DM: 'Dominica',
    EC: 'Ecuador',
    EG: 'Egypt',
    ER: 'Eritrea',
    EE: 'Estonia',
    ET: 'Ethiopia',
    FJ: 'Fiji',
    FI: 'Finland',
    FR: 'France',
    GA: 'Gabon',
    GM: 'Gambia',
    GE: 'Georgia',
    DE: 'Germany',
    GH: 'Ghana',
    GI: 'Gibraltar',
    GR: 'Greece',
    GL: 'Greenland',
    GD: 'Grenada',
    GP: 'Guadeloupe',
    GU: 'Guam',
    GT: 'Guatemala',
    GG: 'Guernsey',
    GN: 'Guinea',
    GY: 'Guyana',
    HT: 'Haiti',
    HN: 'Honduras',
    HU: 'Hungary',
    IS: 'Iceland',
    IN: 'India',
    ID: 'Indonesia',
    IQ: 'Iraq',
    IE: 'Ireland',
    IL: 'Israel',
    IT: 'Italy',
    JM: 'Jamaica',
    JP: 'Japan',
    JE: 'Jersey',
    JO: 'Jordan',
    KZ: 'Kazakhstan',
    KE: 'Kenya',
    KI: 'Kiribati',
    KP: "Korea, Democratic People'S Republic of",
    KW: 'Kuwait',
    KG: 'Kyrgyzstan',
    LA: "Lao People'S Democratic Republic",
    LV: 'Latvia',
    LB: 'Lebanon',
    LS: 'Lesotho',
    LR: 'Liberia',
    LI: 'Liechtenstein',
    LT: 'Lithuania',
    LU: 'Luxembourg',
    MO: 'Macao',
    MG: 'Madagascar',
    MW: 'Malawi',
    MY: 'Malaysia',
    MV: 'Maldives',
    ML: 'Mali',
    MT: 'Malta',
    MQ: 'Martinique',
    MR: 'Mauritania',
    MU: 'Mauritius',
    YT: 'Mayotte',
    MX: 'Mexico',
    MC: 'Monaco',
    MN: 'Mongolia',
    MS: 'Montserrat',
    MA: 'Morocco',
    MZ: 'Mozambique',
    MM: 'Myanmar',
    NA: 'Namibia',
    NR: 'Nauru',
    NP: 'Nepal',
    NL: 'Netherlands',
    NI: 'Nicaragua',
    NE: 'Niger',
    NG: 'Nigeria',
    NU: 'Niue',
    NO: 'Norway',
    OM: 'Oman',
    PK: 'Pakistan',
    PW: 'Palau',
    PA: 'Panama',
    PY: 'Paraguay',
    PE: 'Peru',
    PH: 'Philippines',
    PN: 'Pitcairn',
    PL: 'Poland',
    PT: 'Portugal',
    QA: 'Qatar',
    RE: 'Reunion',
    RO: 'Romania',
    RW: 'RWANDA',
    WS: 'Samoa',
    SN: 'Senegal',
    SC: 'Seychelles',
    SG: 'Singapore',
    SK: 'Slovakia',
    SI: 'Slovenia',
    SO: 'Somalia',
    ES: 'Spain',
    SD: 'Sudan',
    SR: 'Suriname',
    SZ: 'Swaziland',
    SE: 'Sweden',
    CH: 'Switzerland',
    TJ: 'Tajikistan',
    TH: 'Thailand',
    TG: 'Togo',
    TK: 'Tokelau',
    TO: 'Tonga',
    TN: 'Tunisia',
    TR: 'Turkey',
    TM: 'Turkmenistan',
    TV: 'Tuvalu',
    UG: 'Uganda',
    UA: 'Ukraine',
    UY: 'Uruguay',
    UZ: 'Uzbekistan',
    VU: 'Vanuatu',
    VE: 'Venezuela',
    YE: 'Yemen',
    ZM: 'Zambia',
    ZW: 'Zimbabwe',
    AX: 'Åland Islands',
    AS: 'American Samoa',
    AG: 'Antigua and Barbuda',
    BA: 'Bosnia and Herzegovina',
    BV: 'Bouvet Island',
    IO: 'British Indian Ocean Territory',
    BN: 'Brunei Darussalam',
    BF: 'Burkina Faso',
    CV: 'Cape Verde',
    KY: 'Cayman Islands',
    CF: 'Central African Republic',
    CX: 'Christmas Island',
    CC: 'Cocos (Keeling) Islands',
    CD: 'Congo, The Democratic Republic of the',
    CK: 'Cook Islands',
    CR: 'Costa Rica',
    CZ: 'Czech Republic',
    DO: 'Dominican Republic',
    SV: 'El Salvador',
    GQ: 'Equatorial Guinea',
    FK: 'Falkland Islands (Malvinas)',
    FO: 'Faroe Islands',
    GF: 'French Guiana',
    PF: 'French Polynesia',
    TF: 'French Southern Territories',
    GW: 'Guinea-Bissau',
    HM: 'Heard Island and Mcdonald Islands',
    VA: 'Holy See (Vatican City State)',
    HK: 'Hong Kong',
    IR: 'Iran, Islamic Republic Of',
    IM: 'Isle of Man',
    KR: 'Korea, Republic of',
    LY: 'Libyan Arab Jamahiriya',
    MK: 'Macedonia, The Former Yugoslav Republic of',
    MH: 'Marshall Islands',
    FM: 'Micronesia, Federated States of',
    MD: 'Moldova, Republic of',
    AN: 'Netherlands Antilles',
    NC: 'New Caledonia',
    NZ: 'New Zealand',
    NF: 'Norfolk Island',
    MP: 'Northern Mariana Islands',
    PS: 'Palestinian Territory, Occupied',
    PG: 'Papua New Guinea',
    PR: 'Puerto Rico',
    RU: 'Russian Federation',
    SH: 'Saint Helena',
    KN: 'Saint Kitts and Nevis',
    LC: 'Saint Lucia',
    PM: 'Saint Pierre and Miquelon',
    VC: 'Saint Vincent and the Grenadines',
    SM: 'San Marino',
    ST: 'Sao Tome and Principe',
    SA: 'Saudi Arabia',
    CS: 'Serbia and Montenegro',
    SL: 'Sierra Leone',
    SB: 'Solomon Islands',
    ZA: 'South Africa',
    GS: 'South Georgia and the South Sandwich Islands',
    LK: 'Sri Lanka',
    SJ: 'Svalbard and Jan Mayen',
    SY: 'Syrian Arab Republic',
    TW: 'Taiwan, Province of China',
    TZ: 'Tanzania, United Republic of',
    TL: 'Timor-Leste',
    TT: 'Trinidad and Tobago',
    TC: 'Turks and Caicos Islands',
    AE: 'United Arab Emirates',
    GB: 'United Kingdom',
    US: 'United States',
    UM: 'United States Minor Outlying Islands',
    VN: 'Vietnam',
    VG: 'Virgin Islands, British',
    VI: 'Virgin Islands, U.S.',
    WF: 'Wallis and Futuna',
    EH: 'Western Sahara',
};

export default country_names;
